---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2a
spec:
  securityGroups: 
    - sg-06de63c2800020b49
  subnet: subnet-0baa1512ad89057ed
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2c
spec:
  securityGroups: 
    - sg-06de63c2800020b49
  subnet: subnet-07f252ef1b993b847